version: "3.3"
services:
  strapi:
    image: strapi/strapi
    restart: always
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    links:
      - postgres
    volumes:
      - /etc/infrastructure/strapi:/srv/app
    ports:
      - 1337:1337
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - /etc/infrastructure/postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
